### ISSUE TITLE
add campaign info to class create step

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/teacher#44]
Provide a sentence below the "subject" selection that offers information about what campaigns will be added when this subject is selected, eg:

`You've selected the subject Science. This will add 1 campaign to your class, Trash.`

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/mobilizingcs/teacher/commit/acedca6649e89350cf3c6359ddde7dc2d6be6251.
